---
title: "Titanic Wrangling"
code-fold: false
format: 
  html:
    embed-resources: true

---
In this practice activity you'll continue to work with the titanic dataset in ways that flex what you've learned about both data wrangling and data visualization.

```{python}
import numpy as np
import pandas as pd

data_dir = "https://dlsun.github.io/pods/data/"
df_titanic = pd.read_csv(data_dir + "titanic.csv")
df_titanic.head()
```

# 1. Filter the data to include passengers only. Calculate the joint distribution (cross-tab) between a passenger's class and where they embarked.

```{python}
df_titanic_passengers = df_titanic[(df_titanic['class'] == '1st') | (df_titanic['class'] == '2nd') | (df_titanic['class'] == '3rd')]

df_titanic_passengers
```

```{python}
pd.crosstab(df_titanic_passengers["class"], df_titanic_passengers["embarked"])
```

# 2. Using the joint distribution that calculated above, calculate the following:

* the conditional distribution of their class given where they embarked
* the conditional distribution of where they embarked given their class

Use the conditional distributions that you calculate to answer the following quesitons:

* What proportion of 3rd class passengers embarked at Southampton?
* What proportion of Southampton passengers were in 3rd class?

```{python}
given_embarked = pd.crosstab(df_titanic_passengers["class"], df_titanic_passengers["embarked"], normalize = "columns")
given_class = pd.crosstab(df_titanic_passengers["class"], df_titanic_passengers["embarked"], normalize = "index")

print(given_embarked)
print(given_class)

# of the 709 passangers in 3rd class, 494 embarked at Southampton. About 70% of passangers in 3rd class embarked from Southampton
# of the 914 passangers who embarked from Southampton, 494 were in 3rd class. About 54% of passangers who embarked from Southampton were in 3rd class
```

# 3. Make a visualization showing the distribution of a passenger's class, given where they embarked.

Discuss the pros and cons of using this visualization versus the distributions you calculated before, to answer the previous questions.


```{python}
from plotnine import *

(ggplot(df_titanic_passengers,
aes(
  x = "embarked",
  fill = "class"
))
+ geom_bar(position = "fill")
)
```